#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB_NAME" <<-EOSQL
    CREATE USER "$POSTGRES_USER" WITH ENCRYPTED PASSWORD "$POSTGRES_PASSWORD";
    CREATE DATABASE "$POSTGRES_DB_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB_NAME" TO "$POSTGRES_USER";
EOSQL
